class ListStudent(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.CharField( max_length=50, db_index=True, null=True, blank=True)
    status = models.IntegerField( default=5,db_index=True)
    std_no = models.CharField(null=True,  blank=True, max_length=15)
    name = models.CharField(max_length=50,   db_index=True)
    surname = models.CharField(max_length=50,  db_index=True)
    id_no = models.CharField(max_length=15,  unique=True,db_index=True)
    photo = models.ImageField(upload_to="Student/",  null=True, blank=True,db_index=True)
    class_year = models.IntegerField(db_index=True)
    class_name = models.CharField(max_length=50,db_index=True)
    class_branch = models.CharField(max_length=100,db_index=True)
    mother_name = models.CharField(max_length=100,  db_index=True)
    mother_birthdate = models.CharField(max_length=100,  db_index=True)
    mother_birthplace = models.CharField(max_length=100,  db_index=True)
    mother_phone_mobile = models.CharField(max_length=100,  db_index=True)
    mother_education = models.CharField(max_length=100,  db_index=True)
    mother_job = models.CharField(max_length=100,  db_index=True)
    mother_work = models.CharField(max_length=100,  db_index=True)
    mother_email = models.CharField(max_length=100,  db_index=True)
    father_name = models.CharField(max_length=100,  db_index=True)
    father_birthdate = models.CharField(max_length=100,  db_index=True)
    father_birthplace = models.CharField(max_length=100,  db_index=True)
    father_phone_mobile = models.CharField(max_length=100,  db_index=True)
    father_education = models.CharField(max_length=100,  db_index=True)
    father_job = models.CharField(max_length=100,  db_index=True)
    father_work = models.CharField(max_length=100,  db_index=True)
    father_email = models.CharField(max_length=100,  db_index=True)
    other_name = models.CharField(max_length=100,  db_index=True)
    other_birthdate = models.CharField(max_length=100,  db_index=True)
    other_birthplace = models.CharField(max_length=100,  db_index=True)
    other_phone_mobile = models.CharField(max_length=100,  db_index=True)
    other_education = models.CharField(max_length=100,  db_index=True)
    other_job = models.CharField(max_length=100,  db_index=True)
    other_work = models.CharField(max_length=100,  db_index=True)
    other_email = models.CharField(max_length=100,  db_index=True)
    preregistration_date = models.DateField(db_index=True)
    preregistration_fee = models.DecimalField(max_digits=10,  decimal_places=4, default=0.0000,db_index=True)
    registration_classyear = models.IntegerField(  default=6, db_index=True)
    previous_school = models.IntegerField( db_index=True )
    other_previous_school = models.CharField(max_length=250, db_index=True )
    scholarship = models.IntegerField(  db_index=True)
    uniform = models.BooleanField(default=True, null=False)
    food = models.BooleanField(default=True, null=False)
    transfer = models.BooleanField(default=True, null=False)
    foreign_language = models.CharField(  max_length=50, null=True, blank=True)
    local_language = models.CharField(  max_length=50, null=True, blank=True)
    acceptance_local_name = models.CharField(max_length=50, unique=True)
    acceptance_foreign_name = models.CharField(max_length=50, unique=True)
    gender = models.IntegerField(  db_index=True)
    birthdate = models.DateField( db_index=True)
    birthplace = models.CharField( max_length=250, db_index=True)
    blood_type = models.CharField( max_length=10,db_index=True)
    address = models.TextField(null=True, blank=True)
    phone_home = models.CharField( max_length=50, null=True, blank=True,db_index=True)
    phone_mobile = models.CharField( max_length=50, null=True, blank=True,db_index=True)
    guardian = models.CharField(max_length=1)
    parent_martial_status = models.IntegerField(  default=1, )
    divorced_mother_marital_status = models.BooleanField(null=True,  blank=True,db_index=True)
    divorced_father_marital_status = models.BooleanField(null=True,  blank=True,db_index=True)
    mother_alive = models.IntegerField( default=1,  db_index=True)
    father_alive = models.IntegerField( default=1,  db_index=True)
    with_whom = models.CharField(max_length=50)
    special_notes = models.TextField(null=True, blank=True)
    health_notes = models.TextField(null=True, blank=True)
    registration_date = models.DateTimeField(db_index=True)#Kayıt Tarihi 
    region_name = models.CharField(max_length=250, db_index=True)
    nationality_local_name = models.CharField(max_length=250, unique=True,db_index=True)
    nationality_foreign_name = models.CharField(max_length=250, unique=True,db_index=True)

    class Meta:
        managed = False
        db_table = 'List_test'
        ordering = ['std_no']